# Generated by Django 4.2.3 on 2023-07-05 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_task_date_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsystem_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='current_status',
            field=models.CharField(choices=[('CR', 'Created'), ('RJ', 'Rejected'), ('FN', 'Finished')], default='CR', max_length=2),
        ),
        migrations.AddField(
            model_name='task',
            name='user_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='MenuPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_point_name', models.CharField(max_length=50)),
                ('current_subsystem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.subsystem')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.menupoint')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='menu_point',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.menupoint'),
        ),
    ]
