# Generated by Django 4.2.3 on 2023-07-05 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_subsystem_remove_task_title_task_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actor', to=settings.AUTH_USER_MODEL),
        ),
    ]
